// Writes the GuestBook and UzoForwarder ABIs to frontend/src/abi.ts so the frontend has typed contract calls.
// `npm run deploy` runs this for you. Run it by hand (`npm run abi`) after changing a contract.
import { writeFileSync } from "node:fs"
import { pathToFileURL } from "node:url"
import type { Abi } from "viem"
import { readForgeAbi } from "./lib/deployments.js"

export function exportAbi(guestBook: Abi, forwarder: Abi): void {
  const body =
    "// Generated by scripts/export-abi.ts from out/GuestBook.sol and out/UzoForwarder.sol. Do not edit by hand.\n" +
    `export const guestBookAbi = ${JSON.stringify(guestBook, null, 2)} as const\n\n` +
    `export const forwarderAbi = ${JSON.stringify(forwarder, null, 2)} as const\n`
  writeFileSync("frontend/src/abi.ts", body)
}

if (import.meta.url === pathToFileURL(process.argv[1]!).href) {
  exportAbi(readForgeAbi("GuestBook"), readForgeAbi("UzoForwarder"))
  console.log("Wrote frontend/src/abi.ts")
}
