// Writes the UzoToken ABI to frontend/src/abi.ts so the frontend has typed contract calls.
// `npm run deploy` runs this for you. Run it by hand (`npm run abi`) after changing the contract.
import { writeFileSync } from "node:fs"
import { pathToFileURL } from "node:url"
import type { Abi } from "viem"
import { readForgeAbi } from "./lib/deployments.js"

export function exportAbi(abi: Abi): void {
  const body = `// Generated by scripts/export-abi.ts from out/UzoToken.sol/UzoToken.json. Do not edit by hand.\nexport const uzoTokenAbi = ${JSON.stringify(abi, null, 2)} as const\n`
  writeFileSync("frontend/src/abi.ts", body)
}

if (import.meta.url === pathToFileURL(process.argv[1]!).href) {
  exportAbi(readForgeAbi("UzoToken"))
  console.log("Wrote frontend/src/abi.ts")
}
