// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import {ERC721Enumerable} from "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {Base64} from "@openzeppelin/contracts/utils/Base64.sol";
import {Strings} from "@openzeppelin/contracts/utils/Strings.sol";

/// @title UzoNFT
/// @notice A paid-mint ERC-721 whose artwork lives fully on chain. Anyone can mint one token per call
/// by paying exactly `mintPrice`, until `maxSupply` tokens exist. The owner can change the price and
/// withdraw the mint proceeds.
/// @dev `tokenURI` builds the JSON metadata and an SVG image in the contract and returns them as a
/// Base64 data URI, so there is no IPFS or server to keep online. ERC721Enumerable adds
/// `tokenOfOwnerByIndex`, which lets a frontend list a wallet's tokens without reading event logs.
contract UzoNFT is ERC721, ERC721Enumerable, Ownable, ReentrancyGuard {
    using Strings for uint256;

    /// @notice Price of one mint, in wei of the native coin (BOT).
    uint256 public mintPrice;

    /// @notice The most tokens that can ever exist. Token IDs run from 1 to maxSupply.
    uint256 public immutable maxSupply;

    event Minted(address indexed to, uint256 indexed tokenId);
    event MintPriceChanged(uint256 oldPrice, uint256 newPrice);
    event Withdrawn(address indexed to, uint256 amount);

    error WrongPayment(uint256 sent, uint256 price);
    error SoldOut();
    error MaxSupplyIsZero();
    error NothingToWithdraw();
    error WithdrawFailed();

    constructor(
        string memory name_,
        string memory symbol_,
        uint256 mintPrice_,
        uint256 maxSupply_,
        address owner_
    ) ERC721(name_, symbol_) Ownable(owner_) {
        if (maxSupply_ == 0) revert MaxSupplyIsZero();
        mintPrice = mintPrice_;
        maxSupply = maxSupply_;
    }

    /// @notice Mints the next token to the caller. Send exactly `mintPrice` with the call.
    /// @return tokenId The ID of the new token.
    function mint() external payable nonReentrant returns (uint256 tokenId) {
        if (msg.value != mintPrice) revert WrongPayment(msg.value, mintPrice);
        uint256 supply = totalSupply();
        if (supply >= maxSupply) revert SoldOut();

        // There is no burn, so the supply only grows and IDs never repeat.
        tokenId = supply + 1;
        emit Minted(msg.sender, tokenId);
        // _safeMint calls onERC721Received when the caller is a contract. nonReentrant stops that
        // callback from minting again inside this call.
        _safeMint(msg.sender, tokenId);
    }

    /// @notice Changes the mint price. Owner only. Tokens already minted are not affected.
    function setMintPrice(uint256 newPrice) external onlyOwner {
        emit MintPriceChanged(mintPrice, newPrice);
        mintPrice = newPrice;
    }

    /// @notice Sends the whole contract balance (the mint proceeds) to the owner. Owner only.
    function withdraw() external onlyOwner nonReentrant {
        uint256 amount = address(this).balance;
        if (amount == 0) revert NothingToWithdraw();
        address to = owner();
        emit Withdrawn(to, amount);
        (bool ok, ) = to.call{value: amount}("");
        if (!ok) revert WithdrawFailed();
    }

    /// @notice How many tokens can still be minted.
    function remainingSupply() external view returns (uint256) {
        return maxSupply - totalSupply();
    }

    /// @notice Returns `data:application/json;base64,...` metadata with an on-chain SVG image.
    function tokenURI(uint256 tokenId) public view override returns (string memory) {
        _requireOwned(tokenId);
        uint256 hue = _hue(tokenId);
        string memory id = tokenId.toString();

        string memory image = Base64.encode(bytes(_svg(id, hue)));
        string memory json = string.concat(
            '{"name":"',
            Strings.escapeJSON(name()),
            " #",
            id,
            '","description":"A fully on-chain NFT on BOT Chain. The image and this metadata are generated by the contract.",',
            '"image":"data:image/svg+xml;base64,',
            image,
            '","attributes":[{"trait_type":"Hue","value":',
            hue.toString(),
            "}]}"
        );
        return string.concat("data:application/json;base64,", Base64.encode(bytes(json)));
    }

    /// @dev A colour from 0 to 359 derived from the ID, so every token looks different but the
    /// same ID always gets the same colour.
    function _hue(uint256 tokenId) internal pure returns (uint256) {
        return uint256(keccak256(abi.encode(tokenId))) % 360;
    }

    /// @dev Single quotes inside the SVG keep it valid inside the JSON string without escaping.
    function _svg(string memory id, uint256 hue) internal pure returns (string memory) {
        string memory h = hue.toString();
        return
            string.concat(
                "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 400 400'>",
                "<defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'>",
                "<stop offset='0' stop-color='hsl(",
                h,
                ",70%,55%)'/><stop offset='1' stop-color='hsl(",
                h,
                ",70%,22%)'/></linearGradient></defs>",
                "<rect width='400' height='400' fill='url(#g)'/>",
                "<text x='200' y='215' text-anchor='middle' dominant-baseline='middle' ",
                "font-family='monospace' font-size='88' font-weight='700' fill='#fff'>#",
                id,
                "</text></svg>"
            );
    }

    // ---------- required overrides: ERC721 and ERC721Enumerable both define these ----------

    function _update(
        address to,
        uint256 tokenId,
        address auth
    ) internal override(ERC721, ERC721Enumerable) returns (address) {
        return super._update(to, tokenId, auth);
    }

    function _increaseBalance(address account, uint128 value) internal override(ERC721, ERC721Enumerable) {
        super._increaseBalance(account, value);
    }

    function supportsInterface(bytes4 interfaceId) public view override(ERC721, ERC721Enumerable) returns (bool) {
        return super.supportsInterface(interfaceId);
    }
}
