import { useEffect, type ReactNode } from "react"
import { formatEther, isAddress, isAddressEqual, type Address } from "viem"
import {
  useAccount,
  useBalance,
  useReadContract,
  useReadContracts,
  useWaitForTransactionReceipt,
  useWriteContract,
} from "wagmi"
import { uzoNftAbi } from "./abi"
import { ConnectButton } from "./components/ConnectButton"
import { TxStatus } from "./components/TxStatus"
import { addressLink, targetChain } from "./wagmi"

const envAddress = import.meta.env.VITE_CONTRACT_ADDRESS
const nftAddress = envAddress && isAddress(envAddress) ? envAddress : undefined

/** The gallery reads one tokenURI per token, so it stops at this many to keep the page quick. */
const GALLERY_LIMIT = 48
const coin = targetChain.nativeCurrency.symbol

export function App() {
  return (
    <div className="page">
      <div className="topbar">
        <span className="badge">{targetChain.name}</span>
        <ConnectButton />
      </div>
      {nftAddress ? <Collection address={nftAddress} /> : <NotDeployed />}
      <footer className="footer">
        <p>Learning template. Not audited. Use test funds only.</p>
        <p>Uzo Labs is an independent project and is not affiliated with or endorsed by BOT Chain.</p>
      </footer>
    </div>
  )
}

function Hero({ eyebrow, title, lede }: { eyebrow: string; title: ReactNode; lede: ReactNode }) {
  return (
    <header className="hero">
      <p className="eyebrow">{eyebrow}</p>
      <h1>{title}</h1>
      <p className="lede">{lede}</p>
    </header>
  )
}

function NotDeployed() {
  return (
    <main className="stack">
      <Hero
        eyebrow="NFT template"
        title="Deploy your collection first"
        lede="This app mints from your NFT contract once it is on chain."
      />
      <section className="card">
        <h2>No contract address yet</h2>
        <p>
          Run <code>npm run deploy</code> in the project folder. It writes <code>VITE_CONTRACT_ADDRESS</code> to{" "}
          <code>frontend/.env</code>. Then restart <code>npm run frontend</code>.
        </p>
      </section>
    </main>
  )
}

function Collection({ address }: { address: Address }) {
  const { address: account, chainId } = useAccount()
  const onRightChain = chainId === targetChain.id
  const nft = { address, abi: uzoNftAbi, chainId: targetChain.id } as const

  // Polling reads instead of event subscriptions: BOT Chain RPCs do not serve eth_getLogs.
  const { data, refetch } = useReadContracts({
    contracts: [
      { ...nft, functionName: "name" },
      { ...nft, functionName: "mintPrice" },
      { ...nft, functionName: "totalSupply" },
      { ...nft, functionName: "maxSupply" },
      { ...nft, functionName: "owner" },
    ],
    allowFailure: false,
    query: { refetchInterval: 10_000 },
  })
  const [name, mintPrice, totalSupply, maxSupply, owner] = data ?? []
  const isOwner = !!account && !!owner && isAddressEqual(account, owner)

  return (
    <main className="stack">
      <Hero
        eyebrow={`On-chain NFT on ${targetChain.name}`}
        title={name ?? "..."}
        lede="Every token's artwork and metadata are generated by the contract itself. Nothing lives on a server."
      />

      <MintCard
        address={address}
        price={mintPrice}
        minted={totalSupply}
        max={maxSupply}
        canMint={!!account && onRightChain}
        onSuccess={refetch}
      />

      {account ? <Gallery address={address} account={account} minted={totalSupply} /> : null}

      {isOwner && onRightChain ? <OwnerCard address={address} minted={totalSupply} onSuccess={refetch} /> : null}
    </main>
  )
}

type MintCardProps = {
  address: Address
  price?: bigint
  minted?: bigint
  max?: bigint
  canMint: boolean
  onSuccess: () => void
}

function MintCard({ address, price, minted, max, canMint, onSuccess }: MintCardProps) {
  const { writeContract, data: hash, isPending, error, reset } = useWriteContract()
  const receipt = useWaitForTransactionReceipt({ hash, chainId: targetChain.id })

  useEffect(() => {
    if (receipt.isSuccess) onSuccess()
  }, [receipt.isSuccess, onSuccess])

  const remaining = minted !== undefined && max !== undefined ? max - minted : undefined
  const soldOut = remaining === 0n
  const busy = isPending || receipt.isLoading
  const receiptError = receipt.data?.status === "reverted" ? new Error("The transaction reverted.") : receipt.error
  const priceText = price === undefined ? "..." : `${formatEther(price)} ${coin}`

  function mint() {
    if (price === undefined) return
    reset()
    writeContract({ address, abi: uzoNftAbi, chainId: targetChain.id, functionName: "mint", value: price })
  }

  return (
    <section className="card" aria-labelledby="mint-title">
      <div className="row">
        <h2 id="mint-title">Mint</h2>
        {soldOut ? <span className="badge">Sold out</span> : null}
      </div>
      <dl>
        <dt>Price</dt>
        <dd className="mono">{priceText}</dd>
        <dt>Minted</dt>
        <dd className="mono">{minted === undefined || max === undefined ? "..." : `${minted} of ${max}`}</dd>
        <dt>Remaining</dt>
        <dd className="mono">{remaining === undefined ? "..." : remaining.toString()}</dd>
        <dt>Contract</dt>
        <dd className="mono">
          <a href={addressLink(address)} target="_blank" rel="noreferrer">
            {address}
          </a>
        </dd>
      </dl>
      <button type="button" onClick={mint} disabled={!canMint || busy || soldOut || price === undefined}>
        {busy ? "Working..." : soldOut ? "Sold out" : `Mint for ${priceText}`}
      </button>
      {canMint ? null : <p className="muted">Connect your wallet on {targetChain.name} to mint.</p>}
      <TxStatus
        hash={hash}
        isSigning={isPending}
        isConfirming={receipt.isLoading}
        isSuccess={receipt.isSuccess && receipt.data?.status === "success"}
        error={error ?? receiptError}
      />
    </section>
  )
}

type Metadata = { name: string; image: string; hue?: number }

/** Decodes `data:application/json;base64,...` from tokenURI. Returns undefined for anything else. */
function decodeTokenUri(uri: string): Metadata | undefined {
  const prefix = "data:application/json;base64,"
  if (!uri.startsWith(prefix)) return undefined
  try {
    const bytes = Uint8Array.from(atob(uri.slice(prefix.length)), (c) => c.charCodeAt(0))
    const json = JSON.parse(new TextDecoder().decode(bytes))
    // Only accept an SVG data URI. It is shown with <img>, which never runs scripts inside the SVG.
    if (typeof json.image !== "string" || !json.image.startsWith("data:image/svg+xml;base64,")) return undefined
    const hue = json.attributes?.find((a: { trait_type?: string }) => a.trait_type === "Hue")?.value
    return { name: String(json.name), image: json.image, hue }
  } catch {
    return undefined
  }
}

function Gallery({ address, account, minted }: { address: Address; account: Address; minted?: bigint }) {
  const nft = { address, abi: uzoNftAbi, chainId: targetChain.id } as const
  // Its own read: ERC-721 balanceOf reverts for the zero address, so it only runs with a wallet.
  // `minted` in the key refetches it as soon as a mint lands.
  const { data: owned } = useReadContract({
    ...nft,
    functionName: "balanceOf",
    args: [account],
    scopeKey: String(minted),
    query: { refetchInterval: 10_000 },
  })
  const count = owned === undefined ? 0 : Number(owned > BigInt(GALLERY_LIMIT) ? GALLERY_LIMIT : owned)

  // Step 1: the IDs this wallet owns, by index (ERC721Enumerable). No event logs needed.
  const ids = useReadContracts({
    contracts: Array.from({ length: count }, (_, i) => ({
      ...nft,
      functionName: "tokenOfOwnerByIndex" as const,
      args: [account, BigInt(i)] as const,
    })),
    query: { enabled: count > 0 },
  })
  const tokenIds = (ids.data ?? []).flatMap((r) => (r.status === "success" ? [r.result] : []))

  // Step 2: the on-chain metadata for each ID.
  const uris = useReadContracts({
    contracts: tokenIds.map((id) => ({ ...nft, functionName: "tokenURI" as const, args: [id] as const })),
    query: { enabled: tokenIds.length > 0 },
  })

  const loading = owned === undefined || ids.isLoading || uris.isLoading

  return (
    <section className="card" aria-labelledby="gallery-title">
      <div className="row">
        <h2 id="gallery-title">My NFTs</h2>
        {owned ? <span className="badge">{owned.toString()} owned</span> : null}
      </div>
      {loading ? (
        <p className="muted">Loading...</p>
      ) : count === 0 ? (
        <p className="muted">You do not own any yet. Mint one above.</p>
      ) : (
        <ul className="gallery">
          {tokenIds.map((id, i) => {
            const result = uris.data?.[i]
            const meta = result?.status === "success" ? decodeTokenUri(result.result) : undefined
            return (
              <li key={id.toString()} className="nft">
                {meta ? (
                  <img src={meta.image} alt={meta.name} width={400} height={400} loading="lazy" />
                ) : (
                  <div className="nft-missing">No image</div>
                )}
                <p className="mono">{meta?.name ?? `#${id}`}</p>
              </li>
            )
          })}
        </ul>
      )}
      {owned !== undefined && owned > BigInt(GALLERY_LIMIT) ? (
        <p className="muted">Showing the first {GALLERY_LIMIT}.</p>
      ) : null}
    </section>
  )
}

type OwnerCardProps = { address: Address; minted?: bigint; onSuccess: () => void }

function OwnerCard({ address, minted, onSuccess }: OwnerCardProps) {
  // `minted` in the key refetches the balance as soon as a mint lands.
  const balance = useBalance({
    address,
    chainId: targetChain.id,
    scopeKey: String(minted),
    query: { refetchInterval: 10_000 },
  })
  const { writeContract, data: hash, isPending, error, reset } = useWriteContract()
  const receipt = useWaitForTransactionReceipt({ hash, chainId: targetChain.id })

  const refetchBalance = balance.refetch
  useEffect(() => {
    if (!receipt.isSuccess) return
    onSuccess()
    refetchBalance()
  }, [receipt.isSuccess, onSuccess, refetchBalance])

  const busy = isPending || receipt.isLoading
  const empty = balance.data?.value === 0n
  const receiptError = receipt.data?.status === "reverted" ? new Error("The transaction reverted.") : receipt.error

  return (
    <section className="card" aria-labelledby="owner-title">
      <div className="row">
        <h2 id="owner-title">Proceeds</h2>
        <span className="badge">Owner only</span>
      </div>
      <p className="amount">
        {balance.data ? formatEther(balance.data.value) : "..."} <span className="muted">{coin}</span>
      </p>
      <button
        type="button"
        className="secondary"
        disabled={busy || empty || !balance.data}
        onClick={() => {
          reset()
          writeContract({ address, abi: uzoNftAbi, chainId: targetChain.id, functionName: "withdraw" })
        }}
      >
        {busy ? "Working..." : empty ? "Nothing to withdraw" : "Withdraw to owner"}
      </button>
      <TxStatus
        hash={hash}
        isSigning={isPending}
        isConfirming={receipt.isLoading}
        isSuccess={receipt.isSuccess && receipt.data?.status === "success"}
        error={error ?? receiptError}
      />
    </section>
  )
}
